### ISSUE TITLE
configurable ssh keys?

### ISSUE THREAD

**Issue by khadrin** [KasperMadsen/storm-deploy-alternative#11]
Hi. Would you accept a patch to make the path to ssh keys (id_rsa, id_rsa.pub) configurable?

Thanks,
Stephen

**Comment by KasperMadsen** [comment]
Hi Stephen,
I would be very happy to accept it as long as it is optional and the
default path remains unchanged :)

Best,
Kasper

2015-05-12 20:40 GMT+02:00 Stephen J. Smith <notifications@github.com>:

**Comment by khadrin** [comment]
Thanks. Gave it a go but didn't have luck on my side. Sorry.
