### ISSUE TITLE
Do you support spot instances?

### ISSUE THREAD

**Issue by hquan** [KasperMadsen/storm-deploy-alternative#15]

**Comment by KasperMadsen** [comment]
Unfortunately no. I am working on a general deployment solution which supports this. It will be ready within a few weeks. Let me know if you are interested in trying it out.

**Comment by mattburns** [comment]
I'd be interested in trying out whatever you have that supports spot instances :)

**Comment by KasperMadsen** [comment]
Due to unforeseen delays, it will be at least one more month. I will make an announcement when launching :)

**Comment by ZumZoom** [comment]
Do you have any updates on it?
