### ISSUE TITLE
Deployoing to multiple availability zones (or regions)

### ISSUE THREAD

**Issue by spicoflorin** [KasperMadsen/storm-deploy-alternative#2]
Hello!
  Is it possible to deploy the nodes of the storm clusters in different Availability Zones (or regions).
  For example I would like to deploy this kind of cluster:
mycluster:
    - m1.medium {MASTER} //-->deployed on region us-west-1
    - m1.medium {WORKER} //-->deployed on region us-west-1
     -m1.medium {WORKER} //-->deployed on region us-east-1
    - m1.medium {ZK} //-->deployed on region us-west-1
     - m1.medium {ZK} //-->deployed on region us-west-1
     m1.medium {ZK} //-->deployed on region us-east-1
Thanks in advance.
  Regards,
 Florin

**Comment by lokeshhctm** [comment]
Is there any update on this?

**Comment by KasperMadsen** [comment]
Not yet - you are welcome to contribute :)

**Comment by KasperMadsen** [comment]
It seems I don't have time to do this within any reasonable timeframe. I will close this issue now.
