### ISSUE TITLE
Creating Storm cluster with specified VPC ID

### ISSUE THREAD

**Issue by barkatdhillon** [KasperMadsen/storm-deploy-alternative#22]
I have created an AMI from an instance with desired VPC attached to it, but when I am creating cluster by giving following configuration, then it is attaching other default VPC to newly created instance. Is there any configuration like region, through which I can mention which VPC it should link with instance?

my-storm-cluster:
    - storm-version "0.9.5"                    # Version of Storm
    - zk-version "3.4.6"                    # Version of Zookeeper
    - image "ap-southeast-1/ami-xxxxxxxxxx"                # Ubuntu 14.04 LTS AMI
    - region "ap-southeast-1"                    # Region
    - r3.large {ZK, WORKER, MASTER, UI}            # Request service
    - remote-exec-preconfig {cd ~, echo hey > hey.txt}
    - remote-exec-postconfig {}

**Comment by KasperMadsen** [comment]
Hi,
VPC is currently not supported. Are you interested in submitting a pull request for this feature? It should be fairly simple with Apache JClouds (see https://jclouds.apache.org/guides/aws-ec2/, section VPC).

**Comment by barkatdhillon** [comment]
Kindly review PR#23

**Comment by KasperMadsen** [comment]
Thanks for the pull request, it is now merged :+1:
