### ISSUE TITLE
What are ec2-identity and ec2-credential?

### ISSUE THREAD

**Issue by rzachariah** [KasperMadsen/storm-deploy-alternative#24]
In the configuration.yaml file, I entered my AWS access key in ec2-identity and my secret key in ec2-credential. Is this correct?

I'm getting a 401 unauthorized when i invoke
java -jar storm-deploy-alternative.jar deploy CLUSTER_NAME

**Comment by KasperMadsen** [comment]
The CLUSTER_NAME is supposed to be replaced by your own cluster definition in the configuration.yaml. The way you have entered your AWS keys sounds to be correct. Please provide full stacktrace of error. Also, please ensure you have no whitespace in your credentials by mistake. Lastly, you should also check if your AWS account has sufficient rights for EC2 (IAM).

**Comment by rzachariah** [comment]
I figured out my problem. I failed to import my public key into EC2. After doing that (for the correct region), I was able to create instances using StormDeployAlternative. Thanks!
