### ISSUE TITLE
Exception encountered when Attaching to Cluster

### ISSUE THREAD

**Issue by rzachariah** [KasperMadsen/storm-deploy-alternative#25]
Hi,

I used StormDeployAlternative to create a two node cluster. The nodes were successfully created on EC2. Then I got an exception when "Attaching to cluster." Log:

```
ubuntu@ip-10-164-0-58:~/storm-deploy-alternative$ java -jar target/storm-deploy-alternative-1.jar deploy testcluster
2016-01-22 15:00:53 [INFO] Initialized cloud provider service
2016-01-22 15:01:06 [INFO] Deploying cluster: testcluster
2016-01-22 15:01:06 [INFO] Starting 1 instance of type m1.medium with daemons [ZK, WORKER, MASTER, UI]
2016-01-22 15:01:06 [INFO] Starting 1 instance(s) of type m1.medium with daemons [WORKER]
2016-01-22 15:02:24 [INFO] Attaching to cluster
Exception in thread "main" java.util.NoSuchElementException
        at com.google.common.collect.Iterators$1.next(Iterators.java:80)
        at dk.kaspergsm.stormdeploy.commands.Deploy.deploy(Deploy.java:70)
        at dk.kaspergsm.stormdeploy.StormDeployAlternative.main(StormDeployAlternative.java:81)
```

**Comment by rzachariah** [comment]
I installed the default jre and jdk on ubuntu. Here's my java version.

```
ubuntu@ip-10-164-0-58:~/storm-deploy-alternative$ java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
```

**Comment by rzachariah** [comment]
So looking at the code, the exception comes from this line.

```
uiPublicAddress = getUINode(config, newNodes).getPublicAddresses().iterator().next();
```

Does stormdeployalternative require that the ec2 instances have Public IP addresses? My ec2 instances are getting created with Private IP addresses only. These are accessible from my work internal network only.

**Comment by KasperMadsen** [comment]
Hi,
The deployment tool assumes there is an public address associated with each node. How do you launch instances with this tool, without having public ips?

If you can provide a reasonable usecase (and explanation), I will update the code, such that it no longer make this assumption :)

Best,
Kasper

**Comment by rzachariah** [comment]
Your tool is able to launch nodes no problem, even though the subnet I am using will not assign public IPs by default. For security reasons, my organization prefers not to assign public IPs to our EC2 instances, and our subnets are configured to not create them. These instances are still accessible through the private IP, but only within our company network.

Using a personal AWS account, I was able to get past this problem, as you can see here.

```
ubuntu@ip-172-31-25-255:~/storm-deploy-alternative$ java -jar target/storm-deploy-alternative-1.jar deploy phoenixcluster
2016-01-22 18:08:18 [INFO] Initialized cloud provider service
2016-01-22 18:08:29 [INFO] Deploying cluster: phoenixcluster
2016-01-22 18:08:29 [INFO] Starting 1 instance of type m1.medium with daemons [ZK, WORKER, MASTER, UI]
2016-01-22 18:08:29 [INFO] Starting 1 instance(s) of type m1.medium with daemons [WORKER]
2016-01-22 18:09:24 [INFO] Attaching to cluster
2016-01-22 18:09:24 [INFO] Configuring instance(s)

2016-01-22 18:14:37 [INFO] User: ubuntu
2016-01-22 18:14:37 [INFO] Started:
2016-01-22 18:14:37 [INFO]      54.165.229.254  [ZK, WORKER, MASTER, UI]
2016-01-22 18:14:37 [INFO]      54.152.50.143   [WORKER]
2016-01-22 18:14:37 [INFO] Storm UI: http://54.165.229.254:8080
2016-01-22 18:14:37 [INFO] Ganglia UI: http://54.165.229.254/ganglia
```

It would be nice to use your tool with my company AWS account (so I don't have to pay for the charges!), but then it would require some change to fit our security policy. If a public IP is not assigned, you can check the instance for a private IP, and access it through that.

**Comment by KasperMadsen** [comment]
I have made a new commit which I expect will fix your problem. Please try again and let me know :)

**Comment by rzachariah** [comment]
Your change worked for me! Storm cluster successfully created on a private network!

I'm now wondering how to give my Storm workers access to AWS services. There already is a credentials file in ~/.aws, but it seems my spout doesn't see it. (I'm trying to get data from Kinesis.) Any tips? Thanks for your help!

**Comment by KasperMadsen** [comment]
Nice :)

I haven't worked with Kinesis yet, so I am not sure about this. If you can get data on S3 with Kinesis, then simply use the s3cmd tool which is installed in the deploy process.

**Comment by rzachariah** [comment]
So the issue isn't specifically with Kinesis, it's about getting access to AWS services from a Storm Worker. There are two choices:
1) Provision the storm worker with an IAM role with sufficient privileges. Can I assign an IAM role using your deploy process?
2) Supply an access key and secret to the worker. The access key and secret is available on the worker node in ~/.aws/credential, but I'm not sure how to make the Storm components (spout, bolt) aware of it.

How does s3cmd get access to AWS?

**Comment by KasperMadsen** [comment]
1) Currently IAM roles are not supported. I would like this, but I won't have time to implement it the next few months. If you need it, consider implementing it (check out JClouds) and make a pull request :)

2) Maybe use the AWS CLI tools from Storm?

s3cmd uses the credentials, see .s3cfg.

**Comment by rzachariah** [comment]
Thanks, again, for fixing this!

By the way, I found a way to give my Storm bolts access to AWS services without using IAM roles. I'm using the ClasspathPropertiesFileCredentialsProvider to supply the credentials in a file.
