### ISSUE TITLE
Restarting a storm cluster

### ISSUE THREAD

**Issue by rzachariah** [KasperMadsen/storm-deploy-alternative#33]
I made a change to zoo.cfg (to enable autopurge), and I'd like to restart zookeeper to apply it. Is there a command for stopping and starting a storm cluster that was deployed through this tool?

Thanks!

**Comment by KasperMadsen** [comment]
To control the storm cluster, you should normally use the storm cli tool or the storm ui. Restarting zookeeper is not possible with these tools, so simply login to the nodes you wish to update and restart the daemon. If you use fault-tolerance within Storm, there shouldn't be any problems.
