### ISSUE TITLE
Target a disk for installation

### ISSUE THREAD

**Issue by ndtreviv** [KasperMadsen/storm-deploy-alternative#34]
Currently, when we use storm-deploy-alternative on AWS it always deploys to /dev/xvda1, which is where the user home directory is:

```
public static List<Statement> download(String stormRemoteLocation) {
    //                 Here ↴ 
    return Tools.download("~/", stormRemoteLocation, true, true, "storm");
}
``` 

However, I want to specifically target the /mnt directory, which sits on /dev/xvdb.

Is this possible? How would I go about doing this without changing user home directories?

Thanks!

**Comment by KasperMadsen** [comment]
That will probably require an update to the deploy tool. I suggest to make a new attribute in the config file called "working_dir" or similar. Then fetch that value instead of defaulting to home. If the value is not provided in the config, then default to home as this is fine for almost all users.

If you make such change, please consider making a pull request. Thanks :)

**Comment by ndtreviv** [comment]
Cool. I'm nearly done getting it working. I just have a question about Configuration and wonder what your preference would be:

In order to do this, I needed to pass the installDir around everywhere, which was frustrating. Instead, once the configuration is parsed I set it as a system property and access it like that, so I no longer need to pass it around. 

I don't like that either.

I'd rather Configuration was static so that config params could be accessed from anywhere without having to pass Configuration around everywhere. 

What do you think? Should I just shut up my bitching and pass that installDir around everywhere instead?

**Comment by ndtreviv** [comment]
PS: I'm happy to make the change to turn Configuration into a static and clean up the method calls.

**Comment by KasperMadsen** [comment]
Thanks for the pull request :+1: ... I think the code is easily understood the way you have done it.
