### ISSUE TITLE
How is this project different from storm-deploy?

### ISSUE THREAD

**Issue by tanaysoni** [KasperMadsen/storm-deploy-alternative#37]
I see that [storm-deploy](https://github.com/nathanmarz/storm-deploy) provides a similar functionality.

It'd be great to have a documentation on the motivation of writing this project and the differences between both the projects.

**Comment by KasperMadsen** [comment]
I am just back from vacation. Give me a few days to add this :)

**Comment by KasperMadsen** [comment]
I have added motivation to the project description :)
