### ISSUE TITLE
S3 Bucket URL not accessible. 

### ISSUE THREAD

**Issue by saubhagyab** [KasperMadsen/storm-deploy-alternative#41]
@KasperMadsen It seems the Storm 1.0.1 and 0.10.0 s3 urls are not accessible due to some rights. It gives access denied. 

Can you please check?

Also can you please add the 3.4.8 zookeeper to the config.

**Comment by KasperMadsen** [comment]
You were right about Storm 1.0.1, but 0.10.0 is ok. I have fixed the permissions for Storm 1.0.1. Zookeeper 3.4.8 is currently not supported by this tool. I will add it later. You can use the available Zookeeper versions just fine.

**Comment by saubhagyab** [comment]
@KasperMadsen Thanks
