### ISSUE TITLE
Storm 1.0.1 Setup

### ISSUE THREAD

**Issue by saubhagyab** [KasperMadsen/storm-deploy-alternative#42]
Hi @KasperMadsen 

It seem after the complete process the daemon processes are not getting started for 1.0.1 version.
There is no error nothing the Storm UI doesn't come up just the ganglia starts.

No Zookeeper.
No Nimbus.
No UI.

Can you please have look? 

Sorry to bother you again and again.

**Comment by KasperMadsen** [comment]
Hi there,
It is no problem. I pride myself that the software should "just work", so it is actually me who are sorry for your trouble. I have looked into it, and it seems the pull request 1bb5d63 is causing your trouble (gives the problem you describe unless an installation directory is provided). Please try updating your configuration with an installation directory, e.g. install-dir "/mnt" and let me know if it solves your problem.

**Comment by saubhagyab** [comment]
Thanks for such a prompt reply I will try it and update the issue.

**Comment by saubhagyab** [comment]
Nope I added - install-dir "~/storm-cluster" but it didn't start the daemons.

**Comment by KasperMadsen** [comment]
Please dont use Tilde. I suspect  that is what is causing the problem.

Den 8. aug. 2016 21.58 skrev "Saubhagya" <notifications@github.com>:

**Comment by saubhagyab** [comment]
So should I do /home/ubuntu/folder-name? as I don't want to install it on the root user.

**Comment by KasperMadsen** [comment]
That looks good to me. If it still doesnt work, send me your configuration.

Den 8. aug. 2016 22.04 skrev "Saubhagya" <notifications@github.com>:

So should I do /home/ubuntu/folder-name? as I don't want to install it on
the root user.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/KasperMadsen/storm-deploy-alternative/issues/42#issuecomment-238359558>,
or mute the thread

**Comment by saubhagyab** [comment]
Thanks it did work.

 Should I close the issue or you wanna close it after adding a line in readme or code fix?

**Comment by KasperMadsen** [comment]
Just keep it open. I will close after bugfix. Great it worked.

Den 8. aug. 2016 22.15 skrev "Saubhagya" <notifications@github.com>:

**Comment by KasperMadsen** [comment]
Fixed...
