### ISSUE TITLE
Default username (ubuntu) no longer works

### ISSUE THREAD

**Issue by thvasilo** [KasperMadsen/storm-deploy-alternative#49]
I think this has to do with the fact that instances have `ec2-user` as their default user now, so if the username is not provided it leads to connection errors.

**Comment by KasperMadsen** [comment]
Please provide more information:
1. Which image are you using? 
2. Does it work if you override the username with the parameter called "image-username" ?

**Comment by thvasilo** [comment]
Hello @KasperMadsen I was trying to use an Amazon Linux AMI which is not supported by this library, so I'll go ahead and close this issue.
